---
os: linux
dist: xenial
language: python
python: 3.7
services: docker

branches:
  only:
  - master
  - travis

jobs:
  include:
    - stage: tests
      script:
      # Common OpenWISP QA
      - pip install openwisp-utils[qa]>=0.4.1
      - openwisp-utils-qa-checks --skip-checkmigrations
      # Setup for Test
      - export hosts="127.0.0.1 dashboard.openwisp.org controller.openwisp.org
                                radius.openwisp.org topology.openwisp.org"
      - sudo bash -c 'echo "${hosts}" >> /etc/hosts'
      - make compose-build
      # Test
      - make develop-runtests
